name: Merge All Changes To Staging

on:
  push:
    branches:
      - dev

jobs:
  merge-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get commit message
        id: commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1 HEAD)"

      - name: Merge changes to staging
        run: |
          git checkout staging
          git merge --no-commit --no-ff dev
          git commit -m "${{ steps.commit.outputs.message }}"
          git push origin staging