name: Merge Dev Into Staging

on:
  push:
    branches:
      - 'dev'

permissions: 
  pull-requests: write
  contents: write

jobs:
  main:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create PR
        id: pull
        run: |
          url=$(gh pr create --base staging --fill | grep -o 'http[s]://[^ ]*')
          echo "PULL_REQUEST_URL=$url" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Automerge
        run: gh pr merge --merge --auto ${{ steps.pull.outputs.PULL_REQUEST_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}