name: Merge Dev Into Staging

on:
  push:
    branches:
      - 'dev'

permissions: 
  pull-requests: write
  contents: write

jobs:
  main:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          commit-message: Automated Pull Request
          title: "[Automated] Merge ${{ github.ref_name }} into staging"
          body: Automated Pull Request
          branch: staging
          add-paths: !*.json

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}